steps:
# Build the Django application Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mukeshbothers/core-web:latest', '.']
  dir: './web'

# Push the Django application Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mukeshbothers/core-web:latest']

# Build the Nginx Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mukeshbothers/core-nginx:latest', './nginx']

# Push the Nginx Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mukeshbothers/core-nginx:latest']

# Apply Kubernetes manifests to deploy the application
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_REGION=asia-south1'
    - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=mukesh'
    - 'CLOUDSDK_CORE_PROJECT=mukeshbothers'

images:
  - 'gcr.io/mukeshbothers/core-web:latest'
  - 'gcr.io/mukeshbothers/core-nginx:latest'

options:
  logging:
    logs_bucket: 'gs://finally_bucket'
