steps:
  # Build the Django application Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mukeshbothers/core-web:latest', '.']  # '.' means the root directory
    dir: './'  # Updated to the correct directory if needed

  # Push the Django application Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mukeshbothers/core-web:latest']

  # Build the Nginx Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mukeshbothers/core-nginx:latest', './nginx']

  # Push the Nginx Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mukeshbothers/core-nginx:latest']

  # Apply Kubernetes manifests to deploy the application
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=mukesh'
      - 'CLOUDSDK_CORE_PROJECT=mukeshbothers'

images:
  - 'gcr.io/mukeshbothers/core-web:latest'
  - 'gcr.io/mukeshbothers/core-nginx:latest'

logsBucket: 'gs://finally_bucket'
