steps:
  # Build the Django application Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mukeshbothers/core-web-v2:latest', '.']
    dir: './'  # This points to the root directory where your Dockerfile is located

  # Push the Django application Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mukeshbothers/core-web-v2:latest']

  # Build the Nginx Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mukeshbothers/core-nginx-v2:latest', '-f', 'nginx/dockerfile.nginx', 'nginx']
    dir: './'  # This points to the root directory but Dockerfile is in 'nginx'

  # Push the Nginx Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mukeshbothers/core-nginx-v2:latest']

  # Apply Kubernetes manifests to deploy the application
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-south1-a'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=naman'
      - 'CLOUDSDK_CORE_PROJECT=mukeshbothers'

images:
  - 'gcr.io/mukeshbothers/core-web-v2:latest'
  - 'gcr.io/mukeshbothers/core-nginx-v2:latest'

logsBucket: 'gs://finally_bucket'
