apiVersion: v1
kind: Secret
metadata:
  name: web-app-secret
type: Opaque
stringData:
  # Django settings
  SECRET_KEY: "django-insecure-we4am0xy3$9+%vtmm@jxe!t9s1khr7o8d7u+#x4wxkvwa-o6xj"
  DEBUG: "False"
  ALLOWED_HOSTS: "34.93.15.248"

  # Database settings
  DB_NAME: "Mukesh"
  DB_USER: "root"
  DB_PASSWORD: "Nj9685070940"
  DB_HOST: "db-service"
  DB_PORT: "3306"

  # Google OAuth2
  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "839841504969-hjpdcf09j7hs7sp4ht2pah8l26j9ovgu.apps.googleusercontent.com"
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "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"

  # Twilio settings
  TWILIO_ACCOUNT_SID: "AC45daf80c65ebd12a7a1d91340f5d8aa4"
  TWILIO_AUTH_TOKEN: "31242dad01385092852b0fe22cdd145c"
  TWILIO_VERIFY_SID: "VA3223ffa6144df33a06901a5a749a1335"
  TWILIO_FROM_NUMBER: "+918770500434"

  # Cashfree settings
  CASHFREE_APP_ID: "TEST1027118633f310e1279b8d22f0cb68117201"
  CASHFREE_SECRET_KEY: "cfsk_ma_test_fadb26ec62fa38ad9e158c014b6153e9_c3b4285a"
  CASHFREE_URL: "https://sandbox.cashfree.com/pg/orders"

  # Email settings
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_HOST_USER: "njbhandari4@gmail.com"
  EMAIL_HOST_PASSWORD: "vzvavrabyoynadhx"
  DEFAULT_FROM_EMAIL: "your-email@gmail.com"
