# Generated by Django 4.1.12 on 2024-05-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='special_product',
        ),
        migrations.DeleteModel(
            name='SpecialSaleProduct',
        ),
    ]
