# Generated by Django 4.1.12 on 2024-05-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_specialproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='unit',
            field=models.CharField(choices=[('10gm', '10 Grams'), ('50gm', '50 Grams'), ('100gm', '100 Grams'), ('250gm', '250 Grams'), ('500gm', '500 Grams'), ('1kg', '1 Kilogram'), ('10kg', '10 Kilogram'), ('50kg', '50 Kilogram'), ('100kg', '100 Kilogram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
