# Generated by Django 4.1.12 on 2024-05-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_specialproduct_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialproduct',
            name='units',
        ),
    ]
