# Generated by Django 4.1.12 on 2024-05-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_specialproduct_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='Subproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subproduct'),
        ),
    ]
