# Generated by Django 4.1.12 on 2024-05-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_unit_subproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='subproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subproduct'),
        ),
    ]
