# Generated by Django 4.1.12 on 2024-05-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_cartitem_subproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
