# Generated by Django 4.1.12 on 2024-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_specialproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialproduct',
            name='carousel_image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images'),
        ),
    ]
