# Generated by Django 4.1.12 on 2024-06-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_coupon_specialproduct_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='home.coupon'),
        ),
    ]
