# Generated by Django 4.1.12 on 2024-06-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_subproduct_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('', 'None'), ('new', 'New'), ('best_seller', 'Best Seller')], default='', max_length=20),
        ),
    ]
