# Generated by Django 4.1.12 on 2024-06-09 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_subproduct_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='tag',
            field=models.CharField(blank=True, choices=[('', 'None'), ('new', 'New'), ('best_seller', 'Best Seller'), ('combo_bundle', 'Combo/Bundle')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ComboBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('subproducts', models.ManyToManyField(related_name='combo_bundles', to='home.subproduct')),
            ],
        ),
    ]
