# Generated by Django 4.1.12 on 2024-06-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_subproduct_tag_combobundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('new', 'New'), ('best_seller', 'Best Seller'), ('combo_bundle', 'Combo/Bundle')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='tag',
        ),
        migrations.AddField(
            model_name='subproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subproducts', to='home.tag'),
        ),
    ]
