# Generated by Django 4.1.12 on 2024-06-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='tags',
        ),
        migrations.AddField(
            model_name='subproduct',
            name='tag',
            field=models.CharField(blank=True, choices=[('', 'None'), ('new', 'New'), ('best_seller', 'Best Seller'), ('combo_bundle', 'Combo/Bundle')], default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
