# Generated by Django 4.1.12 on 2024-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_subproduct_tags_subproduct_tag_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='combobundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bundle_images/'),
        ),
    ]
