# Generated by Django 4.1.12 on 2024-06-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_combobundle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combobundle',
            name='image',
        ),
        migrations.AddField(
            model_name='combobundle',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cart'),
        ),
    ]
