# Generated by Django 4.1.12 on 2024-06-10 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_combobundle_image_combobundle_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='combobundle',
            name='minimum_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='combobundle',
            name='minimum_quantity',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
