# Generated by Django 4.1.12 on 2024-06-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_combobundle_minimum_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combobundle',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.unit'),
        ),
    ]
