# Generated by Django 4.1.12 on 2024-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_combobundle_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_combo_bundle',
            field=models.BooleanField(default=False),
        ),
    ]
