# Generated by Django 4.1.12 on 2024-06-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_cartitem_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='tag',
            field=models.CharField(blank=True, choices=[('', 'None'), ('new', 'New'), ('best_seller', 'Best Seller'), ('combo', 'Combo')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='tag',
            field=models.CharField(blank=True, choices=[('', 'None'), ('new', 'New'), ('best_seller', 'Best Seller'), ('combo', 'Combo')], default='', max_length=20),
        ),
    ]
