# Generated by Django 4.1.12 on 2024-06-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_cartitem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('5kg', '5 Kilograms'), ('10kg', '10 Kilograms'), ('20kg', '20 Kilograms')], max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='ComboBundle',
        ),
    ]
