# Generated by Django 4.1.12 on 2024-06-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_bucket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='size',
            field=models.CharField(choices=[('5kg', '5kg'), ('10kg', '10kg'), ('20kg', '20kg')], max_length=20),
        ),
    ]
