# Generated by Django 4.1.12 on 2024-06-30 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_bucket_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bucket'),
        ),
    ]
