# Generated by Django 4.1.12 on 2024-07-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_subproduct_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bucket'),
        ),
    ]
