# Generated by Django 4.1.12 on 2024-07-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_videorequest_delete_appliedcoupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videorequest',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='videorequest',
            name='subproduct_id',
        ),
        migrations.AddField(
            model_name='videorequest',
            name='subproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subproduct'),
        ),
        migrations.AlterField(
            model_name='videorequest',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
    ]
