# Generated by Django 5.0.6 on 2024-07-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_videorequest_unit_videorequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
