# Generated by Django 5.0.6 on 2024-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_videorequest_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorequest',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
