# Generated by Django 4.1.12 on 2024-08-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_emaillog_invoice_order_ownerdetails_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='progress_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20),
        ),
    ]
