# Generated by Django 4.1.12 on 2024-08-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.JSONField(default=list),
        ),
    ]
