# Generated by Django 4.1.12 on 2024-08-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
    ]
