# Generated by Django 5.1 on 2024-10-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_order_total_quantity_orderitem_unit_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_quantity',
            new_name='total_unit_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
