# Generated by Django 4.1.12 on 2024-08-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_orderitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
