# Generated by Django 5.1 on 2024-10-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_orderitem_image_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
