# Generated by Django 4.1.12 on 2024-08-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_orderitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='placed', max_length=20),
        ),
    ]
