# Generated by Django 5.1 on 2025-02-14 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_orderitem_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_details',
            field=models.TextField(default='No address details provided', verbose_name='Address Details'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing Address'), ('delivery', 'Delivery Address')], max_length=10, verbose_name='Address Type'),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(choices=[('Shivpuri', 'Shivpuri'), ('Indore', 'Indore')], max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=10, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='GST Rate'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_before_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Before GST'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Quantity (kg)'),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='account_number',
            field=models.CharField(help_text='Enter the bank account number.', max_length=20, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='address',
            field=models.TextField(help_text="Enter the owner's address.", verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='contact_number',
            field=models.CharField(help_text='Enter the contact number.', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='gst_number',
            field=models.CharField(help_text='Enter the GST number.', max_length=15, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{15}$')], verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='ifsc_code',
            field=models.CharField(help_text='Enter the IFSC code (e.g., KKBR2345677).', max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$')], verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='upi_id',
            field=models.CharField(help_text='Enter the UPI ID (e.g., 8770500434@ybl).', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+$')], verbose_name='UPI ID'),
        ),
    ]
